// Hier staan alle spelletjes.
// Elk spelletje is een los HTML-bestand in de map public/spelletjes.
// achtergrond en accent bepalen de kleur van het kaartje.

export const spelletjes = [
  {
    naam: "gusts-frietkot",
    titel: "Gust's Frietkot",
    info: "Bedien het frietkot!",
    bestand: "/spelletjes/gusts-frietkot.html",
    achtergrond: "#fbe3de",
    accent: "#b05555",
  },
  {
    naam: "frietkot-chaos",
    titel: "Frietkot Chaos",
    info: "Nog een frietkot vol actie!",
    bestand: "/spelletjes/frietkot-chaos.html",
    achtergrond: "#f6e6d2",
    accent: "#cc8844",
  },
  {
    naam: "bouwbende",
    titel: "BouwBende",
    info: "Bouw je eigen stad!",
    bestand: "/spelletjes/bouwbende.html",
    achtergrond: "#f7f2d2",
    accent: "#c9b536",
  },
  {
    naam: "honden-vs-katten",
    titel: "Honden vs Katten",
    info: "Kies een kant en speel!",
    bestand: "/spelletjes/honden-vs-katten.html",
    achtergrond: "#dff0df",
    accent: "#6fa86f",
  },
  {
    naam: "ik-leer-typen",
    titel: "Ik Leer Typen",
    info: "Oefen met typen op het toetsenbord.",
    bestand: "/spelletjes/ik-leer-typen.html",
    achtergrond: "#dde8f5",
    accent: "#5b8fc9",
  },
  {
    naam: "mijn-mannetje",
    titel: "Mijn Mannetje",
    info: "Grote stad spel!",
    bestand: "/spelletjes/mijn-mannetje.html",
    achtergrond: "#f8dde8",
    accent: "#d9638c",
  },
  {
    naam: "outfit-runner",
    titel: "Outfit Runner",
    info: "Ren en verzamel leuke outfits!",
    bestand: "/spelletjes/outfit-runner.html",
    achtergrond: "#ecdff7",
    accent: "#9a7cc0",
  },
  {
    naam: "pokemon-go",
    titel: "Pokémon GO",
    info: "Vang Pokémon!",
    bestand: "/spelletjes/pokemon-go.html",
    achtergrond: "#fbe3de",
    accent: "#b05555",
  },
  {
    naam: "pokemon-avontuur",
    titel: "Pokemon Avontuur",
    info: "Een simpel Pokemon-avontuur.",
    bestand: "/spelletjes/pokemon-avontuur.html",
    achtergrond: "#f6e6d2",
    accent: "#cc8844",
  },
  {
    naam: "pokemon-bos-avontuur",
    titel: "Pokemon Bos Avontuur",
    info: "De ultieme versie!",
    bestand: "/spelletjes/pokemon-bos-avontuur.html",
    achtergrond: "#f7f2d2",
    accent: "#c9b536",
  },
  {
    naam: "turbo-race",
    titel: "Turbo Race!",
    info: "Race zo snel mogelijk!",
    bestand: "/spelletjes/turbo-race.html",
    achtergrond: "#dff0df",
    accent: "#6fa86f",
  },
  {
    naam: "snake-neon",
    titel: "Snake Neon",
    info: "Het slangenspel, maar neon!",
    bestand: "/spelletjes/snake-neon.html",
    achtergrond: "#dde8f5",
    accent: "#5b8fc9",
  },
  {
    naam: "speelhal",
    titel: "Speelhal",
    info: "Een hele speelhal vol spelletjes!",
    bestand: "/spelletjes/speelhal.html",
    achtergrond: "#f8dde8",
    accent: "#d9638c",
  },
  {
    naam: "springheld",
    titel: "Springheld",
    info: "Spring van platform naar platform!",
    bestand: "/spelletjes/springheld.html",
    achtergrond: "#ecdff7",
    accent: "#9a7cc0",
  },
  {
    naam: "mijn-tuintje",
    titel: "Mijn Tuintje",
    info: "Kweek je eigen tuintje!",
    bestand: "/spelletjes/mijn-tuintje.html",
    achtergrond: "#fbe3de",
    accent: "#b05555",
  },
  {
    naam: "voetbalspel",
    titel: "Voetbalspel",
    info: "Samen tegen de bot-keeper!",
    bestand: "/spelletjes/voetbalspel.html",
    achtergrond: "#f6e6d2",
    accent: "#cc8844",
  },
  {
    naam: "zwarte-kraai",
    titel: "Zwarte Kraai",
    info: "Een spannend spelletje!",
    bestand: "/spelletjes/zwarte-kraai.html",
    achtergrond: "#f7f2d2",
    accent: "#c9b536",
  },
];
